"""Companies module domain — repository ports."""
from __future__ import annotations

from typing import Protocol
from uuid import UUID

from app.modules.companies.domain.entities import Company, User


class CompanyRepository(Protocol):
    """Port for Company persistence."""

    def get_by_id(self, company_id: UUID) -> Company | None: ...
    def get_by_tax_id(self, tax_id: str) -> Company | None: ...
    def list(self, offset: int = 0, limit: int = 50) -> list[Company]: ...
    def add(self, company: Company) -> Company: ...
    def update(self, company: Company) -> Company: ...
    def delete(self, company_id: UUID) -> bool: ...


class UserRepository(Protocol):
    """Port for User persistence."""

    def get_by_id(self, user_id: UUID) -> User | None: ...
    def get_by_email(self, email: str) -> User | None: ...
    def list_by_company(
        self, company_id: UUID, offset: int = 0, limit: int = 50
    ) -> list[User]: ...
    def add(self, user: User) -> User: ...
    def update(self, user: User) -> User: ...
    def delete(self, user_id: UUID) -> bool: ...
