"""Sales module domain — repository ports."""
from __future__ import annotations

from datetime import date
from typing import Protocol
from uuid import UUID

from app.modules.sales.domain.entities import Sale, SalesBatch


class SaleRepository(Protocol):
    """Port for Sale persistence."""

    def get_by_id(self, sale_id: UUID) -> Sale | None: ...
    def list_by_product_and_range(
        self, product_id: UUID, start: date, end: date
    ) -> list[Sale]: ...
    def list_by_company(
        self, company_id: UUID, offset: int = 0, limit: int = 50
    ) -> list[Sale]: ...
    def add(self, sale: Sale) -> Sale: ...
    def add_bulk(self, sales: list[Sale]) -> list[Sale]: ...
    def delete(self, sale_id: UUID) -> bool: ...


class SalesBatchRepository(Protocol):
    """Port for SalesBatch persistence."""

    def get_by_id(self, batch_id: UUID) -> SalesBatch | None: ...
    def list_by_company(self, company_id: UUID) -> list[SalesBatch]: ...
    def add(self, batch: SalesBatch) -> SalesBatch: ...
    def update(self, batch: SalesBatch) -> SalesBatch: ...
