"""Products module domain — repository ports."""
from __future__ import annotations

from typing import Protocol
from uuid import UUID

from app.modules.products.domain.entities import Category, Product


class CategoryRepository(Protocol):
    """Port for Category persistence."""

    def get_by_id(self, category_id: UUID) -> Category | None: ...
    def list_by_company(self, company_id: UUID) -> list[Category]: ...
    def add(self, category: Category) -> Category: ...
    def update(self, category: Category) -> Category: ...
    def delete(self, category_id: UUID) -> bool: ...


class ProductRepository(Protocol):
    """Port for Product persistence."""

    def get_by_id(self, product_id: UUID) -> Product | None: ...
    def get_by_sku(self, company_id: UUID, sku: str) -> Product | None: ...
    def list_by_company(
        self, company_id: UUID, offset: int = 0, limit: int = 50
    ) -> list[Product]: ...
    def list_active(self, company_id: UUID) -> list[Product]: ...
    def add(self, product: Product) -> Product: ...
    def update(self, product: Product) -> Product: ...
    def delete(self, product_id: UUID) -> bool: ...
