"""Dashboard module domain — repository ports."""
from __future__ import annotations

from typing import Protocol
from uuid import UUID

from app.modules.dashboard.domain.entities import DashboardWidget


class DashboardWidgetRepository(Protocol):
    """Port for DashboardWidget persistence."""

    def get_by_id(self, widget_id: UUID) -> DashboardWidget | None: ...
    def list_by_company(self, company_id: UUID) -> list[DashboardWidget]: ...
    def add(self, widget: DashboardWidget) -> DashboardWidget: ...
    def update(self, widget: DashboardWidget) -> DashboardWidget: ...
    def delete(self, widget_id: UUID) -> bool: ...
    def update_positions(self, company_id: UUID, position_updates: dict[UUID, int]) -> None: ...
